### ISSUE TITLE
Make more csv files that will help us make maps

### ISSUE THREAD

**Issue by josephcyang4459** [Jimhof11/BoatTracker#10]
Use the website linked below to create these csv files (also found in the "resources" channel on Discord)
https://www.nmeagen.org/

**Comment by josephcyang4459** [comment]
If you need help, talk to Connor (client)

**Comment by poudelg25** [comment]
Seven csv files have been created. Need to review them.
[Data_for_map.zip](https://github.com/Jimhof11/BoatTracker/files/10129331/Data_for_map.zip)
