### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by josephcyang4459** [Jimhof11/BoatTracker#3]
This webpage will describe our inspiration for the project and as well as introduce each member of the team.

We could also have a quote or something from each member.

**Comment by imbranch** [comment]
I just realized this would not be best for our project since this product is supposed to be for a "client".  They do not need the creators to have their own page.  For a regular class project, it would be fine, but not for something like this probably.

**Comment by josephcyang4459** [comment]
Oh shoot, ok.
