### ISSUE TITLE
Change the element that contains the options for users to filter maps to a form element

### ISSUE THREAD

**Issue by josephcyang4459** [Jimhof11/BoatTracker#5]

**Comment by imbranch** [comment]
This might not be needed.  We should be able to get the users inputs through javascript and html

**Comment by jcy2000** [comment]
Oh yeah... because it's gonna all be on one webpage?

**Comment by josephcyang4459** [comment]
> This might not be needed. We should be able to get the users inputs through javascript and html

Oh yeah... because it's gonna all be on one webpage?

**Comment by imbranch** [comment]
More so because you can just access the inputs chosen for the filters with simple javascript, example:   
const type = document.getElementById("boatType").value;
I'm not sure making a form is necessary for the current version. 
This may change after we get the working prototype.

**Comment by josephcyang4459** [comment]
Just gonna close this issue then, since it's not really required anymore.

**Comment by josephcyang4459** [comment]
Whoops, gotta close this with the correct message
